---
# tasks file for oracle_instant_client

- name: Import assert.yml
  ansible.builtin.import_tasks:
    file: assert.yml
  run_once: yes
  delegate_to: localhost

- name: Install package
  when:
    - oracle_instant_client_installation_type == "package"
  block:
    - name: Trust Oracle GPG key
      ansible.builtin.rpm_key:
        key: "https://yum.oracle.com/RPM-GPG-KEY-oracle-ol{{ ansible_distribution_major_version }}"
      when:
        - ansible_os_family == "RedHat"

    - name: Install basic package
      ansible.builtin.package:
        name: "{{ oracle_instant_client_package }}"
      when:
        - oracle_instant_client_type in ["basic", "all"]

    - name: Install devel package
      ansible.builtin.package:
        name: "{{ oracle_instant_client_devel_package }}"
      when:
        - oracle_instant_client_type in ["devel", "all"]

- name: Instal zip
  when:
    - oracle_instant_client_installation_type == "zip"
  block:
    - name: Install required packages
      ansible.builtin.package:
        name: "{{ oracle_instant_client_required_packages }}"

    - name: Create /usr/lib/oracle
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop: "{{ oracle_instant_client_zip_directories }}"

    - name: Install devel archive
      ansible.builtin.unarchive:
        src: "{{ oracle_instant_client_devel_archive }}"
        dest: /usr/lib/oracle/
        remote_src: yes
      when:
        - oracle_instant_client_type in ["devel", "all"]

    - name: Install basic archive
      ansible.builtin.unarchive:
        src: "{{ oracle_instant_client_archive }}"
        dest: /usr/lib/oracle/
        remote_src: yes
      when:
        - oracle_instant_client_type in ["basic", "all"]

    - name: Copy binaries
      ansible.builtin.copy:
        src: /usr/lib/oracle/instantclient_21_13/{{ item }}
        dest: /usr/lib/oracle/21/client64/bin/
        mode: '0755'
        remote_src: yes
      loop: "{{ oracle_instant_client_zip_binaries }}"
      when:
        - oracle_instant_client_type in ["basic", "all"]
    
    - name: Copy libraries
      ansible.builtin.copy:
        src: /usr/lib/oracle/instantclient_21_13/{{ item }}
        dest: /usr/lib/oracle/21/client64/lib/{{ item }}
        mode: '0755'
        remote_src: yes
      loop: "{{ oracle_instant_client_zip_libraries }}"
      when:
        - oracle_instant_client_type in ["basic", "all"]

    - name: Link libraries
      ansible.builtin.file:
        src: "{{ item.src}}"
        dest: "{{ item.dest }}"
        state: link
      loop: "{{ oracle_instant_client_zip_links }}"
      loop_control:
        label: "{{ item.dest }}"
      when:
        - oracle_instant_client_type in ["basic", "all"]

    - name: Create /etc/ld.so.conf.d/oracle-instantclient.conf
      ansible.builtin.copy:
        dest: /etc/ld.so.conf.d/oracle-instantclient.conf
        content: /usr/lib/oracle/21/client64/lib
        mode: "0644"
      when:
        - oracle_instant_client_type in ["basic", "all"]
      notify:
        - Run ldconfig
