---
- name: Converge
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: ansible-role-oracle_instant_client
      oracle_instant_client_type: all
      oracle_instant_client_installation_type: zip
