---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Find adrci binary
      ansible.builtin.find:
        path: /usr/lib/oracle
        pattern: adrci
        recurse: true
      register: adrci_binary

    - name: Run adrci binary
      ansible.builtin.shell:
        cmd: "ORACLE_HOME=/tmp {{ adrci_binary.files[0].path }} -v"
        executable: /bin/bash
      changed_when: false

    - name: Find genezi binary
      ansible.builtin.find:
        path: /usr/lib/oracle
        pattern: genezi
        recurse: true
      register: genezi_binary

    - name: Run genezi binary
      ansible.builtin.shell:
        cmd: "ORACLE_HOME=/tmp {{ genezi_binary.files[0].path }} -v"
        executable: /bin/bash
      changed_when: false
