---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Run adrci
      ansible.builtin.shell:
        cmd: "set -o pipefail && echo 'HELP' | /usr/lib/oracle/21/client64/bin/adrci -v"
        executable: /bin/bash
      changed_when: no
      environment:
        ORACLE_HOME: /tmp

    - name: Run genezi
      ansible.builtin.command:
        cmd: /usr/lib/oracle/21/client64/bin/genezi -v
      changed_when: no

    - name: Build an application that needs Oracle Instant client
      block:
        - name: Install pkg-config
          ansible.builtin.package:
            name: pkg-config

        - name: Create oci8.pc
          ansible.builtin.copy:
            dest: /tmp/oci8.pc
            mode: "0644"
            content: |
              version=21.13
              build=client64

              libdir=/usr/lib/oracle/21/client64/lib
              includedir=/usr/include/oracle/21/client64

              Name: oci8
              Description: Oracle database engine
              Version: ${version}
              Libs: -L${libdir} -lclntsh
              Libs.private:
              Cflags: -I${includedir}

        - name: Clone hashicorp/vault-plugin-database-oracle.git
          ansible.builtin.git:
            repo: https://github.com/hashicorp/vault-plugin-database-oracle.git
            version: main
            dest: /tmp/vault-plugin-database-oracle

        - name: Install golang
          ansible.builtin.package:
            name: golang

        - name: Build plugin
          ansible.builtin.command:
            cmd: "go build -o vault-plugin-database-oracle ./plugin"
            chdir: /tmp/vault-plugin-database-oracle
            creates: /tmp/vault-plugin-database-oracle/vault-plugin-database-oracle
          environment:
            PKG_CONFIG_PATH: /tmp
