---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Find installation path
      ansible.builtin.find:
        paths: /usr/lib/oracle
        file_type: directory
      register: oracle_instant_client_installation_path

    - name: Run adrci
      ansible.builtin.shell:
        cmd: "set -o pipefail && echo 'HELP' | {{ oracle_instant_client_installation_path.files[-1].path }}/client64/bin/adrci -v"
        executable: /bin/bash
      changed_when: false
      environment:
        ORACLE_HOME: /tmp

    - name: Run genezi
      ansible.builtin.command:
        cmd: "{{ oracle_instant_client_installation_path.files[-1].path }}/client64/bin/genezi -v"
      changed_when: false
